services:
  ebook-manager:
    build: .
    container_name: ebook-manager
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - ${NAS_PATH}:/books
    environment:
      - BOOKS_PATH=/books
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8