services:
  ebook-manager:
    # 1. Change this line to pull your new automated image from Docker Hub
    image: hajtran/ebooks-directory:latest
    container_name: ebook-manager
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # NAS_PATH se duoc truyen tu giao dien Portainer
      - ${NAS_PATH}:/books
      - ./backend/storage:/app/backend/storage
    environment:
      - BOOKS_PATH=/books
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
